#!/bin/bash

function usage {
	echo "Usage: imake build|java"
}

pushd `dirname "$0"`> /dev/null

JAVA_PROJECT_DIR=../../homekicore

if [ -z $1 ]; then
	usage
elif [ $1 = "build" ]; then
	echo "imake: Building project..."
	rm -f CMakeCache.txt
	cmake -G"Eclipse CDT4 - Unix Makefiles"
	make
elif [ $1 = "java" ]; then
	echo "imake: Generating header files from Java source code..."
	mkdir -p java
	pushd java > /dev/null
	export CLASSPATH=`pwd`
	javac ../../homekicore/src/com/homeki/core/device/tellstick/TellStickNative.java -d .
	javah -jni com.homeki.core.device.tellstick.TellStickNative
	popd > /dev/null
	mv java/*.h include
	rm -rf java
else
	usage	
fi

popd > /dev/null
