/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_homeki_core_device_tellstick_TellStickNative */

#ifndef _Included_com_homeki_core_device_tellstick_TellStickNative
#define _Included_com_homeki_core_device_tellstick_TellStickNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_homeki_core_device_tellstick_TellStickNative
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_homeki_core_device_tellstick_TellStickNative_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
