/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_homeki_core_device_tellstick_TellStickNative */

#ifndef _Included_com_homeki_core_device_tellstick_TellStickNative
#define _Included_com_homeki_core_device_tellstick_TellStickNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_homeki_core_device_tellstick_TellStickNative
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_homeki_core_device_tellstick_TellStickNative_open
  (JNIEnv *, jclass);

/*
 * Class:     com_homeki_core_device_tellstick_TellStickNative
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_homeki_core_device_tellstick_TellStickNative_close
  (JNIEnv *, jclass);

/*
 * Class:     com_homeki_core_device_tellstick_TellStickNative
 * Method:    getDeviceIds
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_homeki_core_device_tellstick_TellStickNative_getDeviceIds
  (JNIEnv *, jclass);

/*
 * Class:     com_homeki_core_device_tellstick_TellStickNative
 * Method:    getDeviceType
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_homeki_core_device_tellstick_TellStickNative_getDeviceType
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
